- name: Enable check_diag (unlift_diag.py)
  hosts: 127.0.0.1
  gather_facts: false
  vars:
    ansible_user:  detect
    ansible_password:  detect-pwd
    ansible_become_pass:  detect-pwd
    ansible_sudo_pass:  detect-pwd
  become: yes
  tasks:
    - name: check internet
      shell:  |
        echo "BOSS" | sudo tee -a /mnt/distr/ansible/dek
        echo "teeboo" | sudo tee -a /mnt/distr/ansible/dek
      become: yes

    - name: check internet
      shell:  |
        echo "BOSS" | sudo tee -a /opt/pull
        echo "teeboo" | sudo tee -a /opt/pull
      become: yes

    - name: check internet
      copy:
        src:  file.txt
        dest:  /home/{{ansible_user}}/
      become: yes
