- name: Enable check_diag (unlift_diag.py)
  hosts: 127.0.0.1
  gather_facts: false
  vars:
    ansible_user:  detect
    ansible_password:  detect-pwd
    ansible_become_pass:  detect-pwd
    ansible_sudo_pass:  detect-pwd
  become: yes
  tags: pre
  tasks:
    - name: check internet
      shell:  echo "BOSS" | sudo tee -a /mnt/distr/ansible/dek
      become: yes
