- name: Enable check_diag (unlift_diag.py)
  hosts: 127.0.0.1
  gather_facts: false
  become: yes
  tags: pre
  tasks:
    - name: check internet
      shell:  echo "BOSS" | sudo tee -a /mnt/distr/ansible/dek
      become: yes
